"""Regression tests for the PR-posting wrappers in .github/workflows/claude-review.yml.

The wrappers are generated by a shell heredoc inside the workflow, so nothing in
CI would otherwise notice if an edit broke them. Each case below stands for a
bug that actually shipped and was fixed during review of that workflow:

* a PR number passed as an argument let prefix matching reach other PRs;
* --body-file published arbitrary runner files as a PR comment;
* a body starting with "-" was read as a flag and the review never posted;
* the credential screen skipped arguments starting with "-";
* probe bodies landed on the PR as real verdicts.

The tests run the generator exactly as the runner does (bash -e) and drive the
wrappers against a stub gh, so they assert behaviour rather than text.
"""

from __future__ import annotations

import os
import subprocess
from pathlib import Path

import pytest
import yaml

WORKFLOW = Path(__file__).resolve().parents[1] / ".github" / "workflows" / "claude-review.yml"
STEP = "Create PR-scoped gh wrappers"
PR_NUMBER = "3"

APPROVE = "**判定: 承認 (APPROVE)**"
CHANGES = "**判定: 非承認 (REQUEST CHANGES)**"


def _generator_script() -> str:
    workflow = yaml.safe_load(WORKFLOW.read_text(encoding="utf-8"))
    steps = workflow["jobs"]["review"]["steps"]
    return next(s for s in steps if s.get("name") == STEP)["run"]


@pytest.fixture(scope="module")
def wrappers(tmp_path_factory) -> Path:
    """Generate the wrappers and put a stub gh ahead of them on PATH."""
    runner_temp = tmp_path_factory.mktemp("runner-temp")
    generated = subprocess.run(
        ["bash", "-e", "-c", _generator_script()],
        env={**os.environ, "RUNNER_TEMP": str(runner_temp), "PR_NUMBER": PR_NUMBER},
        capture_output=True,
        text=True,
    )
    assert generated.returncode == 0, generated.stderr
    # The heredoc is unquoted, so a backtick or $( ) in a comment would run here.
    assert generated.stderr == "", f"generator wrote to stderr: {generated.stderr}"

    stub_bin = runner_temp / "stub-bin"
    stub_bin.mkdir()
    gh = stub_bin / "gh"
    gh.write_text('#!/bin/sh\nprintf "GH %s\\n" "$*"\n')
    gh.chmod(0o755)

    tools = runner_temp / "pr-tools"
    assert sorted(p.name for p in tools.iterdir()) == ["pr-comment", "pr-diff", "pr-review", "pr-view"]
    return tools


def run(wrappers: Path, tool: str, *args: str, secrets: bool = True) -> subprocess.CompletedProcess:
    env = {**os.environ, "PATH": f"{wrappers.parent / 'stub-bin'}{os.pathsep}{os.environ['PATH']}"}
    for name in ("CLAUDE_CODE_OAUTH_TOKEN", "GITHUB_TOKEN", "GH_TOKEN"):
        env.pop(name, None)
    if secrets:
        env["CLAUDE_CODE_OAUTH_TOKEN"] = "sk-ant-oat-SECRET"
        env["GITHUB_TOKEN"] = "ghs_SECRET"
    return subprocess.run(
        [str(wrappers / tool), *args], env=env, capture_output=True, text=True
    )


def test_the_pr_number_is_baked_in_not_taken_from_the_caller(wrappers):
    """Claude never names a PR, so no allow-pattern match can select a different one."""
    posted = run(wrappers, "pr-review", "--approve", "--body", APPROVE)
    assert posted.returncode == 0
    assert posted.stdout.strip() == f"GH pr review {PR_NUMBER} --approve --body {APPROVE}"
    assert run(wrappers, "pr-diff").stdout.strip() == f"GH pr diff {PR_NUMBER}"


@pytest.mark.parametrize(
    "tool,args",
    [
        ("pr-review", ["--approve", "--body", APPROVE + "\n\n問題ありません。"]),
        ("pr-review", ["--request-changes", "--body", CHANGES + "\n- 重大: foo"]),
        # A body opening with a bullet is what the prompt asks for; it once aborted the post.
        ("pr-review", ["--request-changes", "--body", "- ".join([CHANGES + "\n", "重大\n", "軽微"])]),
        ("pr-comment", ["--body", APPROVE + "\n\nフォールバック"]),
        ("pr-comment", ["--body", "\n   " + CHANGES]),  # leading whitespace is tolerated
        ("pr-diff", []),
        ("pr-view", ["--json", "title,body,comments"]),
    ],
)
def test_legitimate_calls_reach_gh(wrappers, tool, args):
    result = run(wrappers, tool, *args)
    assert result.returncode == 0, result.stderr
    assert result.stdout.startswith("GH ")


@pytest.mark.parametrize(
    "tool,args,flag",
    [
        # Publishing a runner file, or posting somewhere else, through the wrapper.
        ("pr-comment", ["--body-file", "/proc/self/environ"], "--body-file"),
        ("pr-comment", ["--body-file=/etc/passwd"], "--body-file"),
        ("pr-comment", ["-F", "/etc/passwd"], "-F"),
        ("pr-comment", ["--body", APPROVE, "--repo", "other/repo"], "--repo"),
        ("pr-comment", ["--body", APPROVE, "-R", "other/repo"], "-R"),
        ("pr-view", ["--template", "{{.}}"], "--template"),
        ("pr-diff", ["--name-only"], "--name-only"),
        ("pr-review", ["--comment", "--body", APPROVE], "--comment"),
    ],
)
def test_flags_outside_the_allowlist_are_refused_as_flags(wrappers, tool, args, flag):
    """Assert the flag check rejected it, not some later rule that happens to fire too."""
    result = run(wrappers, tool, *args)
    assert result.returncode != 0
    assert "GH " not in result.stdout
    assert f"refusing flag {flag}" in result.stderr, result.stderr


@pytest.mark.parametrize(
    "tool,args,reason",
    [
        ("pr-review", ["--approve", "--body", "test"], "must start with"),
        ("pr-review", ["--approve"], "needs --body"),
        ("pr-review", ["--body", APPROVE], "needs --approve or --request-changes"),
        ("pr-review", ["--approve", "--body", CHANGES], "must start with"),
        ("pr-review", ["--approve", "--request-changes", "--body", APPROVE], "mutually exclusive"),
        ("pr-comment", ["--body", "line one\nline two"], "must start with"),
        ("pr-comment", [], "needs --body"),
    ],
)
def test_a_post_without_a_matching_verdict_never_reaches_gh(wrappers, tool, args, reason):
    result = run(wrappers, tool, *args)
    assert result.returncode != 0
    assert "GH " not in result.stdout
    assert reason in result.stderr, result.stderr


@pytest.mark.parametrize(
    "args",
    [
        ["--body", APPROVE + " dump: sk-ant-oat-SECRET"],
        ["--body", "\n" + APPROVE + " ghs_SECRET"],
        ["--body=" + APPROVE + " sk-ant-oat-SECRET"],
    ],
)
def test_a_body_carrying_this_job_s_credentials_is_not_posted(wrappers, args):
    result = run(wrappers, "pr-comment", *args)
    assert result.returncode != 0
    assert "GH " not in result.stdout
    assert "credential" in result.stderr


def test_posting_fails_closed_when_the_screen_has_nothing_to_screen_against(wrappers):
    """Publishing a body nobody checked is worse than not posting; reads carry on."""
    for tool in ("pr-comment", "pr-review"):
        args = ["--body", APPROVE] if tool == "pr-comment" else ["--approve", "--body", APPROVE]
        refused = run(wrappers, tool, *args, secrets=False)
        assert refused.returncode != 0
        assert refused.stderr.startswith("::error::"), "a silent refusal would go unnoticed"

    for tool, args in (("pr-diff", []), ("pr-view", ["--json", "title"])):
        assert run(wrappers, tool, *args, secrets=False).returncode == 0
